### ISSUE TITLE
New project is missing } from Logger.cs

### ISSUE THREAD

**Issue by MarshMello0** [DankuwOs/VTOLVRModLoader-Templates#2]
After updating to the latest template version, 1.0.3, when creating a new project it fails to build. 

There is an error in Logger.cs, it is missing a final `}`, however I can see it there perfectly fine in this repo on line 29.
https://github.com/DankuwOs/VTOLVRModLoader-Templates/blob/13b0b2b0128d7e356ad4fd31b9356f2d8dff5492/content/VtolModTemplate/Logger.cs#L25-L29

**Comment by MarshMello0** [comment]
Okay now looking at both versions of Logger.cs, mine doesn't have `LogDetail(object message)`, so I guess its just an update that is pending to be pushed to NuGet which has the fix

**Comment by DankuwOs** [comment]
i think i fixed this by just removing that, no clue why it happened
